apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s

configMapGenerator:
  - name: hotgraph-environment
    behavior: create
    literals:
      - HOTGRAPH_ENVIRONMENT=dev
      - HOTGRAPH_PRODUCTION_CLAIM=false
