apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - api-pvc.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - qdrant-statefulset.yaml
  - object-storage.yaml
  - prometheus.yaml
  - grafana.yaml
  - service.yaml
  - ingress.yaml
